ETicaret2022/Controllers/SepetController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ETicaret2022.Models;
using Microsoft.AspNet.Identity;

namespace ETicaret2022.Controllers
{
    [Authorize]
    public class SepetController : Controller
    {

        ETicaret2022Entities db = new ETicaret2022Entities();
        public ActionResult SepeteEkle(int? adet,int id)
        {
            Urunler urun = db.Urunler.Find(id);

            string userID = User.Identity.GetUserId();

            Sepet sepettekiurun = db.Sepet.FirstOrDefault(x => x.UrunID == id && x.UserID == userID);
            

            if(sepettekiurun==null)
            {
                Sepet yeniurun = new Sepet()
                {
                    Adet = adet??1,
                    UrunID=id,
                    ToplamTutar=urun.UrunFiyati*(adet??1),
                    UserID=userID                     
                };
                db.Sepet.Add(yeniurun);              
            }
            else
            {
                sepettekiurun.Adet = sepettekiurun.Adet + (adet??1);
                sepettekiurun.ToplamTutar = sepettekiurun.Adet * urun.UrunFiyati;
            }
            db.SaveChanges();

            return RedirectToAction("Index");
        }
    
        public ActionResult Index()
        {
            string userID = User.Identity.GetUserId();
           
            var sepet = db.Sepet.Where(x => x.UserID == userID).Include(u => u.Urunler);

            return View(sepet.ToList());
        }

        public ActionResult SepetGuncelle(int? adet,int? id)
        {
            if(id==null)
            {
                return new HttpStatusCodeResult(System.Net.HttpStatusCode.BadRequest);
            }

            Sepet sepet = db.Sepet.Find(id);

            if(sepet==null)
            {
                return HttpNotFound();
            }

            Urunler urun = db.Urunler.Find(sepet.UrunID);

            sepet.Adet = adet ?? 1;
            sepet.ToplamTutar = sepet.Adet * urun.UrunFiyati;
            db.SaveChanges();

            return RedirectToAction("Index");

        }

        public ActionResult Sil(int id)
        {
            Sepet sepet = db.Sepet.Find(id);
            db.Sepet.Remove(sepet);
            db.SaveChanges();

            return RedirectToAction("Index");
        }
    }
}

ETicaret2022/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    @{ 
        bool admin = User.IsInRole("Admin");
    }
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("E-Ticaret", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("AnaSayfa", "Index", "Home")</li>
                    @if (admin)
                    {
                        <li>@Html.ActionLink("Kategoriler", "Index", "Kategori")</li>
                        <li>@Html.ActionLink("Ürünler", "Index", "Urunler")</li>
                    }

                    @if (Request.IsAuthenticated)
                    {            
                        <li>@Html.ActionLink("Siparişlerim", "Index", "Siparis")</li>
                    <li>@Html.ActionLink("Sepetim", "Index", "Sepet")</li>
                    }

                    <li>@Html.ActionLink("Hakkında", "About", "Home")</li>
                    <li>@Html.ActionLink("İletişim", "Contact", "Home")</li>
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>